CLUSTER CategoryProduct USING categoryproductprimary; 
CLUSTER Photo USING photoprimary; 
CLUSTER Review USING reviewprimary; 
CLUSTER Orders USING orderuser; 
CLUSTER Favorite USING favoriteuser;
CLUSTER Address USING AddressUser;
CLUSTER FavoriteList USING FavoriteListUser; 
CLUSTER ProductOrder USING ProductOrderPosition; 
CLUSTER ProductCart USING ProductCartPosition;