CLUSTER CategoryProduct USING categoryproductprimary;
CLUSTER Product USING product_pkey;
CLUSTER Photo USING photoprimary;
CLUSTER Review USING reviewprimary;
CLUSTER Orders USING orderuser;
CLUSTER Favorite USING favoriteuser;
CLUSTER FavoriteList USING FavoriteListUser;
CLUSTER ProductOrder USING ProductOrderPosition;
CLUSTER ProductCart USING ProductCartPosition;